version: 2.1
orbs:
  node: circleci/node@6.1.0
  coveralls: coveralls/coveralls@2.2.1

jobs:
  test_and_build:
    executor:
      name: node/default
      tag: 21.1.0
      resource_class: medium
    steps:
      - checkout
      - run:
          name: Remove Old Yarn Version
          command: sudo rm -rf /usr/local/bin/yarn /usr/local/bin/yarnpkg
      - node/install-yarn:
          version: 4.0.0
      - node/install-packages:
          pkg-manager: yarn
          with-cache: true
      - run:
          name: Lint the Source Code
          command: yarn lint
      - run:
          name: Test the Library
          command: yarn test --runInBand
      - run:
          name: Generate the API Documents
          command: yarn doc
      - run:
          name: Build the Library in Development Mode
          command: yarn build:dev
      - run:
          name: Build the Library in Production Mode
          command: yarn build

workflows:
  build_workflow:
    jobs:
      - test_and_build:
          filters:
            branches:
              only: master
